#ifndef __SYMBOLS_H__

#define __SYMBOLS_H__
#define END 0
#define ARRAY 1
#define BEGIN 2
#define BY 3
#define DO 4
#define ELSE 5
#define ELSIF 6
#define EXIT 7
#define WHILE 8
#define IS 9
#define IF 10
#define LOOP 11
#define RETURN 12
#define NOT 13
#define OF 14
#define PROCEDURE 15
#define PROGRAM 16
#define READ 17
#define THEN  18
#define FOR 19
#define TO 20
#define TYPE 21
#define VAR 22
#define WRITE 23
#define RECORD 24
#define CONSTANT 25
#define STRING_LITERAL 26
#define ADD 27
#define SUB 28
#define MUL 29
#define DIV 30
#define MOD 31
#define OR_OP 32
#define LE_OP 33
#define GE_OP 34
#define LT_OP 35
#define GT_OP 36
#define EQ_OP 37
#define NE_OP 38
#define AND_OP 39
#define OPEN_BR 40
#define CLOSE_BR 41
#define OPEN_CURLY 42
#define CLOSE_CURLY 43
#define OPEN_SQUARE 44
#define CLOSE_SQUARE 45
#define OPEN_SQ_ANGL 46
#define CLOSE_SQ_ANGL 47
#define COMMA 48
#define COLON 49
#define ASSIGN 50
#define DOT 51
#define IDENTIFIER 52
#define END_OF_INSTRUCTION 53

#endif